### ISSUE TITLE
SelectableSection in iOS 11 jumping when selected o deselected

### ISSUE THREAD

**Issue by jjmaceda** [xmartlabs/Eureka#1253]
I'm using the swift 3.2 brach, using a SelectableSection<ImageCheckRow> that comes from the source, if I compile with Xcode 9 and run in the simulator or real device each time I selected or deselect a row the text jump, however if I try the 10.3.1 simulator all works normally as before, maybe some one can give me any clue of why this happing
here it is a video for demostration

https://www.youtube.com/watch?v=v18fahDxWVM

Thanks!

**Comment by mtnbarreto** [comment]
This issue was already fixed. Please use last Eureka release.

**Comment by jjmaceda** [comment]
Good day, we are still having the same issue in the latest release 4.0.1, any idea?, thanks!!

https://www.youtube.com/watch?v=sxe67m8mqZM
